before_script:
    - python --version
    - python -m pip install -r requirements.txt
    - python -m pip install .

stages:
    - Flake8

flake8:
    stage: Flake8
    script:
    - python -m pip install flake8
    - python -m flake8 bidscoin
