image: "python:3.6"


variables:
  RUN_MAIN: "python3 $CI_PROJECT_DIR/bidsme/bidsme.py"
  RUN_PREP: "$RUN_MAIN prepare"
  RUN_MAP: "$RUN_MAIN map"
  RUN_PROC: "$RUN_MAIN process"
  RUN_BIDS: "$RUN_MAIN bidsify"
  EXAMPLE_URL: "https://gitlab.uliege.be/CyclotronResearchCentre/Public/bidstools/bidsme/bidsme_example/-/archive/master/"
  EXAMPLE_DIR: "bidsme_example-master"

cache:
  paths:
    - .cache/pip

before_script: 
  - python --version
  - mkdir -p .cache/pip
  - pip --cache-dir=.cache/pip install -r requirements.txt
  - pip --cache-dir=.cache/pip install flake8

stages:
  - test
  - get_examples
  - run_examples

flake8:
  stage: test
  script:
    - python -m flake8 bidscoin
  #only:
  #  - tags
  #  - dev
  #  - master
    
include_test:
  stage: test
  script:
    - $RUN_MAIN --help
    - $RUN_MAIN --version
    - $RUN_PREP --help
    - $RUN_MAP --help
    - $RUN_PROC --help
    - $RUN_BIDS --help
  #only:
  #  - tags
  #  - dev
  #  - master

get_examples:
  stage: get_examples
  artifacts:
    paths:
      - $EXAMPLE-DIR
    expire_in: 1 day
  script: 
    - wget -nv $EXAMPLE_URL/$EXAMPLE_DIR.tar.gz
    - tar -xzf $EXAMPLE_DIR.tar.gz

example1:
  stage: run_examples
  script:
    - cd $EXAMPLE_DIR/example1
    - $RUN_PREP source/ renamed/ -r nii=MRI --part-template resources/participants.json --plugin resources/plugins/rename_plugin.py
