image: "python:3.6"

cache:
  paths:
    - .cache/pip

before_script: 
  - python --version
  - mkdir -p .cache/pip
  - pip --cache-dir=.cache/pip install -r requirements.txt
  - pip --cache-dir=.cache/pip install flake8

stages:
  - test

flake8:
  stage: test
  script:
    - python -m flake8 bidscoin
  only:
    - tags
    - dev
    - master
    
include_test:
  stage: test
  script:
    - python3 bidsme/bidsme.py --help
    - python3 bidsme/bidsme.py --version
    - python3 bidsme/bidsme.py prepare --help
    - python3 bidsme/bidsme.py map --help
    - python3 bidsme/bidsme.py process --help
    - python3 bidsme/bidsme.py bidsify --help
  only:
    - tags
    - dev
    - master

