image: "python:3.6"

variables:
  RUN: "python3 ${CI_PROJECT_DIR}/bidsme/bidsme.py"
  EXAMPLE_URL: "https://gitlab.uliege.be/CyclotronResearchCentre/Public/bidstools/bidsme/bidsme_example/-/archive/master/"
  EXAMPLE_DIR: "bidsme_example-master"

cache:
  paths:
    - .cache/pip

before_script: 
  - python --version
  - mkdir -p .cache/pip
  - pip --cache-dir=.cache/pip install -r requirements.txt
  - pip --cache-dir=.cache/pip install flake8
  - pip --cache-dir=.cache/pip install xlrd

stages:
  - test
  - get_examples
  - run_examples

flake8:
  stage: test
  script:
    - python -m flake8 bidscoin
    
include_test:
  stage: test
  script:
    - $RUN --help
    - $RUN --version
    - $RUN process --help
    - $RUN prepare --help
    - $RUN bidsify --help
    - $RUN map --help

get_examples:
  stage: get_examples
  artifacts:
    paths:
      - $EXAMPLE_DIR
    expire_in: 1 day
  script: 
    - wget -nv $EXAMPLE_URL/$EXAMPLE_DIR.tar.gz
    - tar -xzf $EXAMPLE_DIR.tar.gz
    - ls

example1:
  stage: run_examples
  script:
    - ls
    - cd $EXAMPLE_DIR/example1
    - $RUN prepare source/ renamed/ -r nii=MRI --part-template resources/participants.json --plugin resources/plugins/rename_plugin.py
